### ISSUE TITLE
Missing the list of features (analyzed problems) and Javadocs

### ISSUE THREAD

**Issue by stIncMale** [vladmihalcea/hypersistence-optimizer#1]
Hi Vlad,

There are multiple things I'd like to mention with regard to the documentation:
1. I was not able to find the list of all problems that Hypersistence Optimizer is able to detect. It would be good to have it and maintain updated for each new version of the tool.
2. I did not find Javadocs for the API privided by the tool. All the current docs mentions is "check your application logs", but what logging library is used by the tool, how to we feed it the logging configs from our application? Someone may also want to grab the problems programmatically and log them explicitly somewhere separately without relying on the tool logging.
3. Is my understanding correct that Hypersistence Optimizer is a dynamic analyzer? I.e. after calling the `HypersistenceOptimizer.init` method (which probably mainly registers Hibernate listeners?), one need to actually use Hibernate ORM to generate the events which are analyzed by the tool. In other words calling _only_ `new HypersistenceOptimizer(new HibernateConfig(sessionFactory)).init()` does not produce the report with problems. If yes, It would be great to have it explicitly explained in the docs. If no, it would still be great to have a quick explanation of what to expect from the tool: whether it does a static or dynamic analysis.

**Comment by vladmihalcea** [comment]
Thanks for you feedback.

I plan on adding more docs in the following weeks. There will be a dedicated:

- User Guide which lists all the features and optimization events
- a dedicated Installation Guide
- How to Guides for various use cases

There is an option to grab the events programmatically, and that's also going to be covered by the User Guide.

Calling `init` is everything you need to do. The tool does the dynamic analysis for you, indeed.

This is just the initial release, so stay tuned for more to come: features, docs, examples.

**Comment by vladmihalcea** [comment]
@stIncMale Would you mind taking a look at the [User Guide](https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/) and let me know if it covers this issue already?

**Comment by stIncMale** [comment]
@vladmihalcea 

> Hypersistence Optimizer is a dynamic analysis tool

I thought it's a dynamic analysis because I expected that an application should use JPA/Hibernate ORM while operating in the regular mode in order for the tool to produce events, but this turned out to not be the case: all analysis events are produced by the time the `HypersistenceOptimizer.init` method returns. This means that **the tool does static analysis**.

The enumeration and description of all events were added, which is great.

I am not sure why you are not publishing the Javadocs for the API of the tool. But given that the API is tiny and probably all explained in the tutorial, it may not be a problem.

So yes, the User Guide covers this issue.

**Comment by vladmihalcea** [comment]
For the moment, this tool only analyzes the mappings and soon it will support the configurations as well. I might add support for statistics in the future.

The JavaDcos are published for all the public classes the user is supposed to interact with. The internal classes are not included, but that's the case with Hibernate ORM too.
