### ISSUE TITLE
Change the Archiva command from archive to archiva in the Installation Guide

### ISSUE THREAD

**Issue by Clopma** [vladmihalcea/hypersistence-optimizer#130]
![image](https://user-images.githubusercontent.com/47386922/104813251-45440380-5808-11eb-894c-51b1f7fbf17a.png)

I think it should be changed from `archive` into `archiva` (tested on archiva 2.2.5)

**Comment by vladmihalcea** [comment]
Thanks for the heads up. It is now fixed both in the [online Installation Guide](https://vladmihalcea.com/hypersistence-optimizer/docs/installation-guide/) and the offline one.
