### ISSUE TITLE
Cannot resolve io.hypersistence:hypersistence-optimizer:1.2.0

### ISSUE THREAD

**Issue by Dos4dev** [vladmihalcea/hypersistence-optimizer#133]
Can't import hypersistence-optimizer via Maven & Gradle into a base project from https://start.spring.io

Suppose the manual import is not a good idea. I appreciate any thoughts and info about this issue.

**Comment by vladmihalcea** [comment]
Hypersistence Optimizer is a commercial product, so you cannot get it from Maven Central. However, once you [purchase a license](https://vladmihalcea.com/hypersistence-optimizer/), you can share the dependency using [Apache Archiva](https://vladmihalcea.com/hypersistence-optimizer/docs/installation-guide/#Installing_the_Maven_dependency_on_Apache_Archiva).

You can use the [Trial version](https://vladmihalcea.teachable.com/p/hypersistence-optimizer-trial) to see how many issues the product can detect in your project, although you will have to buy the actual product to know exactly what causes those issues.

This GitHub project contains examples only that demonstrate how to set up the tool and how to use it.
