### ISSUE TITLE
Add a configuration option to disable the printing of the Hypersistence Optimize banner

### ISSUE THREAD

**Issue by s-jepsen** [vladmihalcea/hypersistence-optimizer#134]
Is it possible to disable the Hypersistence banner, when being a registered user?

**Comment by vladmihalcea** [comment]
I don't think I added this feature, but I can surely add a configuration option for this.

**Comment by s-jepsen** [comment]
Thanks.
It's very noisy in our ci.-build logs.

**Comment by vladmihalcea** [comment]
@s-jepsen No worries. I started working on it and will release the `2.3.1` version when this is done.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by vladmihalcea** [comment]
@s-jepsen The 2.3.1 version has been released and provides this feature you requested. Cheers.
