### ISSUE TITLE
Prevent the BidirectionalSynchronizationEvent from triggering for immutable collections

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hypersistence-optimizer#141]
If the bidirectional collection association is annotated with the `@Immutable` annotation, then the `BidirectionalSynchronizationEvent` should not be triggered since the collection won't ever modify.

**Comment by henke77** [comment]
Hi @vladmihalcea,
there ist a similar issue regarding the rule
`MAJOR - The [...] element-collection in the [...] entity requires all child operations to be executed from the parent side, hence, if you want to add or remove a child element, you always need to fetch the collection. Consider using a bidirectional one-to-many association instead which allows you to operate on the @ManyToOne side without having to fetch the collection in the parent entity.`

Also here we have marked the relation as @Immutable - and thus would not expect the event to be triggered.

**Comment by vladmihalcea** [comment]
Makes sense. Thanks for the tip

**Comment by vladmihalcea** [comment]
Fixed.
