### ISSUE TITLE
Prevent the FlushModeAutoEvent from triggering for native SQL queries when the Session is using FlushMode.MANUAL

### ISSUE THREAD

**Issue by perch24** [vladmihalcea/hypersistence-optimizer#142]
Hibernate sets the flush mode to MANUAL when executing a read-only transaction. This trigger a FlushModeAutoEvent for native queries even though it won't need to flush for a read-only transaction. I've worked around this by adding an event filter that checks if the current transaction is read-only, but this should be the default behavior.

**Comment by vladmihalcea** [comment]
Thanks for spotting this use case. It surely shouldn't trigger that event when flushing is set to MANUAL mode.

**Comment by vladmihalcea** [comment]
Fixed.
