### ISSUE TITLE
Feature request: Support for ignoring events by using annotation.

### ISSUE THREAD

**Issue by natami** [vladmihalcea/hypersistence-optimizer#159]
Implement support for ignoring event warnings/errors using an annotation - something like @SuppressHypersistenceEvent(PaginationWithoutOrderByEvent.class).

Any thoughts on this? :)

**Comment by vladmihalcea** [comment]
You can easily do that with an `EventFilter` that you provide during configuration. Check out [this User Guide](https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#EventFilter) section for more details.

I believe that a programmatic approach is far superior to any annotation.
