### ISSUE TITLE
Unexplainable OneToOneWithoutMapsIdEvent with unidirectional one-to-one

### ISSUE THREAD

**Issue by pkernevez** [vladmihalcea/hypersistence-optimizer#179]
I have the following message, I can't understand:
```CRITICAL - OneToOneWithoutMapsIdEvent - The [fees] one-to-one association in the [InstrumentEntity] entity is using a separate Foreign Key to reference the parent record. Consider using @MapsId so that the identifier is shared with the parent row. For more info about this event, check out this User Guide link - https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#OneToOneWithoutMapsIdEvent```

I try to have a unidirectional one-to-one, and maps the parent ID as the child PK.
This is my configuration:
```java
@Entity
@Table(name = "INSTRUMENT")
public class InstrumentEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_INSTRUMENT")
    @SequenceGenerator(name = "SEQ_INSTRUMENT", sequenceName = "SEQ_INSTRUMENT", allocationSize = 1)
    private Long id;

    @OneToOne(fetch = FetchType.LAZY, orphanRemoval = true, cascade = CascadeType.ALL)
    @JoinColumn(name = "INSTRUMENT_FEE_ID")
    @MapsId("ID") // Necessary because in contrary with the documentation, it's not using ID but INSTRUMENT_INSTRUMENT_FEE_ID that don't exist
    private InstrumentFeeEntity fees;

}
```
And 
```java
@Entity
@Table(name = "INSTRUMENT_FEE")
public class InstrumentFeeEntity {

    @Id
    private Long id;
}
```

Should I miss something or is it a false positive error ?

**Comment by vladmihalcea** [comment]
Isn't this a duplicate of #178?

**Comment by pkernevez** [comment]
Yes, it's a duplicate due to github issue
