### ISSUE TITLE
HypersistenceOptimizer: Symbol not found

### ISSUE THREAD

**Issue by AlexanderNZ** [vladmihalcea/hypersistence-optimizer#180]
Hi All,

I'm having trouble installing the trial for hypersistence optimizer. I want to roll it out in my org but also want a bit more detail before buying.

Here's what I've done:
- Download the trial zip (version 2.6.0-trial)
- Unzipped the archive
- Installed in my local maven repository using ` ./maven-install.sh`

```bash
❯ ./maven-install.sh
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial/hypersistence-optimizer-2.6.0-trial.jar
[INFO] Installing /var/folders/s4/4b8kj2052yz941j71t7003pc0000gp/T/mvninstall10688612564219904417.pom to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial/hypersistence-optimizer-2.6.0-trial.pom
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial-sources.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial/hypersistence-optimizer-2.6.0-trial-sources.jar
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial-javadoc.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial/hypersistence-optimizer-2.6.0-trial-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.151 s
[INFO] Finished at: 2022-09-27T10:29:04+13:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial-jre6.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial-jre6/hypersistence-optimizer-2.6.0-trial-jre6.jar
[INFO] Installing /var/folders/s4/4b8kj2052yz941j71t7003pc0000gp/T/mvninstall2608047261612511560.pom to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial-jre6/hypersistence-optimizer-2.6.0-trial-jre6.pom
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial-jre6-sources.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial-jre6/hypersistence-optimizer-2.6.0-trial-jre6-sources.jar
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial-jre6-javadoc.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial-jre6/hypersistence-optimizer-2.6.0-trial-jre6-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.122 s
[INFO] Finished at: 2022-09-27T10:29:04+13:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ standalone-pom ---
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial-jakarta.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial-jakarta/hypersistence-optimizer-2.6.0-trial-jakarta.jar
[INFO] Installing /var/folders/s4/4b8kj2052yz941j71t7003pc0000gp/T/mvninstall5140198703164644350.pom to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial-jakarta/hypersistence-optimizer-2.6.0-trial-jakarta.pom
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial-jakarta-sources.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial-jakarta/hypersistence-optimizer-2.6.0-trial-jakarta-sources.jar
[INFO] Installing /Users/Alex/Downloads/hypersistence-optimizer-2.6.0-trial/lib/hypersistence-optimizer-2.6.0-trial-jakarta-javadoc.jar to /Users/Alex/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial-jakarta/hypersistence-optimizer-2.6.0-trial-jakarta-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.118 s
[INFO] Finished at: 2022-09-27T10:29:05+13:00
[INFO] ------------------------------------------------------------------------
```

- Added the maven dependency to the project

![image](https://user-images.githubusercontent.com/7684198/192386485-bb10ba9a-525a-402f-9387-a73f78dabfc6.png)
![image](https://user-images.githubusercontent.com/7684198/192386575-b35ca159-8f07-4243-814f-22149c4771b9.png)

- I have not changed any logging settings as I just wanted to get it running, but don't think this would result in the dependency not being picked up
- I'm on Hibernate 5.6.3 so sckipped the 'Decorating the Persistence Unit' Section
- Everything so far looks like it has worked and been fine. When I come to step 6: Instantiating Hypersistence Optimizer I am on Spring Boot and so have done the below, per the installation guide:
![image](https://user-images.githubusercontent.com/7684198/192387053-05d09bc7-39c2-4db1-8892-7a9f67aaee4b.png)

- This is as far as I've gotten. The dependency looks installed, I can see it in my project dependency tree, but my IDE (IntelliJ) can't detect it or import the symbol
- I tried to follow the Spring Boot example repo, and manually added the dependencies that project uses: https://github.com/vladmihalcea/hypersistence-optimizer/blob/a35b0dbc6c003e660f52a205d7c3ab11b04ef3d3/hypersistence-optimizer-test-case/src/test/java/io/hypersistence/optimizer/util/AbstractHypersistenceOptimizerTest.java#L3 but these are not detected either:

![image](https://user-images.githubusercontent.com/7684198/192387433-a6819c6e-ce70-47ea-b29c-b0b0a1be1a33.png)

The contents of `~/.m2/repository/io/hypersistence/hypersistence-optimizer/2.6.0-trial` are:

![image](https://user-images.githubusercontent.com/7684198/192388252-5739f285-82cc-40b1-a19f-fc2fe913ce68.png)

I can't think of why this might be happening. Has anyone encountered this before? I'm sure it's something simple that I've missed, but I've also gone through the install doc a few times now and haven't found any steps that I've missed (aside from configuring the logger)

Is anyone able to spot anything or offer any advice?

**Comment by vladmihalcea** [comment]
You can use the [`trial`](https://github.com/vladmihalcea/hypersistence-optimizer/tree/trial), which provides various examples that work just fine with the trial version.

In your case, you can check out [this Spring Boot example](https://github.com/vladmihalcea/hypersistence-optimizer/tree/trial/hypersistence-optimizer-spring-boot-example).

First, try to run the tests from Maven. If it works in Maven, but it does not work in IntelliJ IDEA, then you know it's an IDE problem, in which case you could try a different IDEA version.

**Comment by AlexanderNZ** [comment]
Thanks, Vlad

Looks like it was a Gradle issue. I needed to add `mavenLocal()` to my `build.gradle` - for projects where you are pulling in your own libraries this is probably quite a common thing, but for me it was not :)

All fixed.

**Comment by vladmihalcea** [comment]
I'm glad you found the problem. Cheers!
