### ISSUE TITLE
java.lang.NoSuchMethodException: io.hypersistence.optimizer.hibernate.decorator.Hibernate43SessionFactoryDecorator.<init>(org.hibernate.SessionFactory)

### ISSUE THREAD

**Issue by hannibal218bc** [vladmihalcea/hypersistence-optimizer#182]
I'm trying to setup this tool for a Hibernate 4.3 project (native - no Spring, no JPA, no Jakarta; runs on Java 11/12 with `hypersistence-optimizer-2.6.0-trial-jre6.jar`), but run into this exception when calling `HypersistenceHibernatePersistenceProvider.decorate( this.sessionFactoryHibernate )`:

```
java.lang.NoSuchMethodException: io.hypersistence.optimizer.hibernate.decorator.Hibernate43SessionFactoryDecorator.<init>(org.hibernate.SessionFactory)
	at java.base/java.lang.Class.getConstructor0(Class.java:3354)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2558)
	at io.hypersistence.optimizer.util.ReflectionUtils.newInstance(ReflectionUtils.java:144)
	at io.hypersistence.optimizer.util.ReflectionUtils.newInstance(ReflectionUtils.java:89)
	at io.hypersistence.optimizer.hibernate.decorator.HypersistenceHibernatePersistenceProvider.decorate(HypersistenceHibernatePersistenceProvider.java:76)
```

And it's true, the `Hibernate43SessionFactoryDecorator`s only constructor is declared as `Hibernate43SessionFactoryDecorator(org.hibernate.engine.spi.SessionFactoryImplementor delegate);`

The actual type of the session factory being passed is `org.hibernate.internal.SessionFactoryImpl`, which implements `SessionFactoryImplementor` so the call should have worked, it seems that just the constructor lookup is wrong?

Thanks!

**Comment by vladmihalcea** [comment]
Can you provide a replicating test case with the setup you tried so I could investigate it?

**Comment by hannibal218bc** [comment]
I had hoped you'd say that it's clearly the `Hibernate43SessionFactoryDecorator` constructor that need to be changed... ;-)

Alright, I'll try to come up with an example project, thanks!

**Comment by hannibal218bc** [comment]
Hi again,

here's the test case: https://github.com/Handig-Eekhoorn/Hypersistence-Tests

You should be able to run it by `mvn compile exec:java`. The result will be the exception posted above. Thank you for investigating!

**Comment by vladmihalcea** [comment]
Thanks.

**Comment by vladmihalcea** [comment]
@hannibal218bc In your test, what happens if you replace:

`var sessionFactoryHypersistence = HypersistenceHibernatePersistenceProvider.decorate( sessionFactoryHibernate );`

with 

`SessionFactory sessionFactoryHypersistence = HypersistenceHibernatePersistenceProvider.decorate( sessionFactoryHibernate );`

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by hannibal218bc** [comment]
> Fixed.

Awesome, thank you!

**Comment by vladmihalcea** [comment]
It's now available in the Full Version and I'm now merging to the Trial.

**Comment by vladmihalcea** [comment]
@hannibal218bc The fix is now available in the Trial Version as well.

**Comment by hannibal218bc** [comment]
I've already bought the license earlier today ;+)

**Comment by vladmihalcea** [comment]
@hannibal218bc Thanks, and enjoy using it.
