### ISSUE TITLE
(How to) retrieve the original Connection from a SessionDelegator?

### ISSUE THREAD

**Issue by hannibal218bc** [vladmihalcea/hypersistence-optimizer#184]
Hi,

some places in the application I'm analyzing retrieve the `java.sql.Connection` from a `Session` like this:

```java
		if (hibSession instanceof SessionImpl){
			return ((SessionImpl) hibSession).connection();
		}
		if (hibSession instanceof StatelessSessionImpl){
			return ((StatelessSessionImpl) hibSession).connection();
		}
```

When using the optimizer, the session objects are of type `SessionDelegator` and the above code doesn't work. However, the type already has a `public Session getOriginalSession()` method, so I'd like to do something like this:

```java
		if (hibSession instanceof SessionDelegator) {
			return getConnectionFromSession(((SessionDelegator) hibSession).getOriginalSession());
		}
```

However, `SessionDelegator` is not visible... would it be possible to add a common supertype for the various delegators, and the `public getOriginalSession()` declaration there? Or is there a better way to achieve this...?

Thank you!

**Comment by vladmihalcea** [comment]
You can use the `doReturningWork` method against the `Session`, and it will work the same even if the `SessionDelegator` is used:

`Connection connection = session.doReturningWork(c -> c);`

**Comment by hannibal218bc** [comment]
Thanks!
