### ISSUE TITLE
Detect whole query cache invalidations when executing native SQL queries

### ISSUE THREAD

**Issue by jiri-pejchal** [vladmihalcea/hypersistence-optimizer#188]
It would be nice if the Hypersistence Optimizer could detect whole query cache invalidations caused by native DML queries that don't specify synchronized entity/query space.

Developers often forget to add a synchronized entity to native DML queries, leading to performance degradation.

**Comment by vladmihalcea** [comment]
That's a wonderful idea. I shall definitely add support for it!

**Comment by vladmihalcea** [comment]
Fixed.
