### ISSUE TITLE
UUID types are handled as "large objects"

### ISSUE THREAD

**Issue by eximius313** [vladmihalcea/hypersistence-optimizer#19]
When I run `hypersistence-optimizer` on my project, it printed this warning:
```
00:10:10.852 [pool-1-thread-1] [warn] Hypersistence Optimizer - MAJOR - LargeColumnEvent - The [uuid] attribute in the [model.User] entity is mapped to a large column type. You should use the @DynamicUpdate annotation so that the UPDATE statement contains only the columns that have been modified by the currently running Persistence Context. For more info about this event, check out this User Guide link - https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#LargeColumnEvent
```
however, `User.uuid` looks like this:
```
  @NotNull
  @Column(name = "uuid", nullable = false, unique = true)
  private UUID uuid = UUID.randomUUID();
```
I'm using PostgreSQL which handles UUIDs just fine (https://www.postgresql.org/docs/9.1/datatype-uuid.html), therefore I'm not sure if this warning is valid

**Comment by vladmihalcea** [comment]
It is still valid. A UUID takes 128 bits and the extra space is amplified by every Foreign Key. A more compact identifier is usually a better default choice.

**Comment by eximius313** [comment]
1) It's not Primary nor Foreign key - it's just regular field (used for REST operations).
2) why `String`s are not treated as "large object", then? Very ofter `String companyName` is larger that 32 characters

**Comment by vladmihalcea** [comment]
It is still valid. A UUID takes 128 bits and the extra space is amplified by every Foreign Key. A more compact identifier is usually a better default choice.

**Comment by vladmihalcea** [comment]
Ok, I'll investigate it if it's not an id.

**Comment by eximius313** [comment]
thanks

**Comment by vladmihalcea** [comment]
Nothing is to be fixed. I just added some tests, and if the UUID is handled by Hibernate as a "large object", then you get this message. However, on PostgreSQL, no such event is logged, hence there is nothing to be fixed.

**Comment by eximius313** [comment]
but `H2` also has support for `UUID` (http://www.h2database.com/html/datatypes.html#uuid_type) so why Hibernate handles it as `LargeObject` ?

**Comment by vladmihalcea** [comment]
That's the way it works. If you want to have that feature implemented, you should open a Hibernate Jira issue and provide a Pull Request for it. For the moment, the `UUIDBinaryType` is the most common way of handling UUID types in Hibernate.
