### ISSUE TITLE
Postgresql reWriteBatchedInserts with jdbcurl

### ISSUE THREAD

**Issue by willome** [vladmihalcea/hypersistence-optimizer#199]
I have tried to add to the postgres jdbc url the **reWriteBatchedInserts** like this: **jdbc:postgres:mydb?reWriteBatchedInserts=true** but hypersistence optimizer still complaining with the **JdbcBatchToBulkInsertEvent** event. 

Well I am not sure if we can pass this parameter to the driver but according th the documentation,it should work https://jdbc.postgresql.org/documentation/use/)

I would like to avoid setting directly the PgDatasource.setReWriteBatchedInserts. Is it possible ?

**Comment by vladmihalcea** [comment]
It could be a false positive, but I'll need a replicating test case to debug it, so that I can see why it's not working as expected.

**Comment by willome** [comment]
My bad, that was my mistake. I am using Testcontainers which automatically adds a **loggerLevel** on the generated url. I was first using **postgreSQLContainer.getJdbcUrl() + "?reWriteBatchedInserts=true"** but it must be changed to **postgreSQLContainer.getJdbcUrl() + "&reWriteBatchedInserts=true"**.

**Comment by vladmihalcea** [comment]
I'm glad you found the culprit.
