### ISSUE TITLE
SecondaryQueryEntityFetchingEvent leads to dead link

### ISSUE THREAD

**Issue by AlexanderNZ** [vladmihalcea/hypersistence-optimizer#201]
Hi Vlad,

I recently got started with Hypersistence Optimizer. I've followed your posts for a long time and really appreciate the hard work on this tool.  When I run my instrumented tests I can see an event it has collected:

`CRITICAL - SecondaryQueryEntityFetchingEvent - The [class $CLASS] entity with the identifier value of [$ID] has been loaded using a secondary query instead of being fetched using a JOIN FETCH clause. For more info about this event, check out this User Guide link - https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#SecondaryQueryEntityFetchingEvent`

As far as I can tell, https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#SecondaryQueryEntityFetchingEvent is a dead link. Is there a different event I should be looking at for this?

Cheers

Alex

**Comment by vladmihalcea** [comment]
Thanks for pointing it out. I updated the online User Guide as well.
