### ISSUE TITLE
Provide a private Maven Repository

### ISSUE THREAD

**Issue by AlexanderNZ** [vladmihalcea/hypersistence-optimizer#202]
Hey Vlad,

I've loved following your articles, I decided to buy a licence and I'm now trying to improve my software with Hypsersistence Optimizer.

I read https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#fail-build-on-issues - I wondered if there is a Maven repository (presumably not Maven Central!) where I can get access to `io.hypersistence:hypersistence-optimizer:2.6.3-jakarta`? I don't operate Apache Archiva or JFrog or anything like that, and I would like to avoid uploading the artefact in my git repo and running the install script and so on each build.

What do you think?

Cheers

Alex

**Comment by vladmihalcea** [comment]
Thanks for buying a license, and enjoy detecting the cause of many performance issues automatically.

There is no private Maven repository at the moment, but I could add one in the future once I find a good solution for that.

>  I would like to avoid uploading the artifact in my git repo and running the install script and so on each build.

You only need to call the install script only once per Optimizer version. Once the artifact is in your local Maven repository, it will be used by all builds.

**Comment by AlexanderNZ** [comment]
Thanks Vlad! 

> You only need to call the install script only once per Optimizer version. Once the artifact is in your local Maven repository, it will be used by all builds.

Sorry! I meant that I don't want to have to script that as part of my Github Action workflow.
I'll wait for that Maven repo. My project uses trunk based dev, so I'll have to pull out the Hypersistence Optimizer implementation into a long lived branch that I merge main into regularly, not an ideal solution but better then not using it.

Thanks again!

**Comment by vladmihalcea** [comment]
I understand. I'll see what I can do about it.

**Comment by vladmihalcea** [comment]
Fixed.
