### ISSUE TITLE
Support for Micronaut

### ISSUE THREAD

**Issue by heyimMarc** [vladmihalcea/hypersistence-optimizer#206]
Hi there, it would be cool to support [Micronaut](https://micronaut.io).

First I thought the integration of the hypersistence-optimizer would be no issue because its using hibernate 5, but I'm getting strange errors until I add the dependency via gradle.

`Could not obtain transaction-synchronized Session for current thread
org.hibernate.HibernateException: Could not obtain transaction-synchronized Session for current thread
	at app//io.micronaut.transaction.hibernate5.MicronautSessionContext.currentSession(MicronautSessionContext.java:91)
`

I'm using Micronaut 3.8.0.

Maybe it's just a simple change to fix this, but at this time it's not working for me. Any ideas?

Let me know if you need more input.

**Comment by vladmihalcea** [comment]
Fixed.
