### ISSUE TITLE
[Feature request] Check for missing indexes

### ISSUE THREAD

**Issue by eximius313** [vladmihalcea/hypersistence-optimizer#21]
In situation like this (please ignore EnumType.STRING - it's really intentional):
```
  @Enumerated(EnumType.STRING)
  @ElementCollection(fetch = FetchType.LAZY)
  @Column(name = "preference", nullable = false)
  @CollectionTable(name = "user_preferences",
    joinColumns = @JoinColumn(name = "user_id", nullable = false)
  )
  private Set<Preference> preferences = new HashSet<>();
```
but it's very probable, that we also need an index here:
`indexes = @Index(name = "idx_user_preferences_user_id", columnList = "user_id")`

Maybe in such obvious situations hypersistence-optimizer could point that out as well?

**Comment by vladmihalcea** [comment]
You can filter Events if they don't apply to you.

By default, it's better to use the Ordinal than the String strategy.

The check for the index is a good idea, but only if it's done against the DB since the schema is better of created with FlywayDB.

**Comment by eximius313** [comment]
I think, that maintaining consistency between database script and entities is a good practice (Indexes included).
Thanks to `hypersistence-optimizer` notification:
1) People who don't maintain consistency will hopefully do that
2) People who do (like me) will spot their mistake

**Comment by vladmihalcea** [comment]
The DB schema is the source of truth, hence defining indexes with annotations is not needed. Usually it's a code smell as hbm2ddl is not meant for production systems.

**Comment by eximius313** [comment]
but it `hbm2ddl` is meant for tests, then you want to have your test schema consistent with production, isn't it?

**Comment by vladmihalcea** [comment]
That's a common misconception. I tried to debunk this myth in the Hibernate User Guide to make it more clear. Hbm2ddl is meant to test the Hibernate-core or to generate some initial schema. If you use FlywayDB in production, why use a different mechanism for your integration tests?

**Comment by eximius313** [comment]
1. Because `hypersistence-optimizer` doesn't work on pure SQL so having Schema&Entity consistent allow us to spot problems with schema (like the one in the issue)
2. H2 is convenient way of testing, but doesn't support everything what PostgreSQL do, so we can't use the same scripts anyway. Of course ideally we should use PostgreSQL for testing as well, but I consider H2 approach as acceptable tradeof

**Comment by vladmihalcea** [comment]
If you read my [High-Performance Java Persistence book](https://vladmihalcea.com/books/high-performance-java-persistence/), you will understand why testing with H2 doesn't really make much sense in 2019. It was a good approach 25 years ago, but Docker changed the game.
