### ISSUE TITLE
[Improvement] Mention PlayFramework in UserGuide

### ISSUE THREAD

**Issue by eximius313** [vladmihalcea/hypersistence-optimizer#22]
For PlayFramework, configuration is a little bit more tricky, therefore I want to share it.
If you don't want to include in doc - I'm fine with closing this issue.
```java
  @Inject
  private JPAApi jpaApi;

  @Test
  public void testOptimizer() {
    jpaApi.withTransaction(em -> {
      final ListEventHandler listEventListener = new ListEventHandler();
      new HypersistenceOptimizer(
          new JpaConfig(em.getEntityManagerFactory())
                      .setEventHandler(new ChainEventHandler(
                              Arrays.asList(
                                      listEventListener,
                                      LogEventHandler.INSTANCE
                              )
                      ))
      ).init();

      assertEquals(0, listEventListener.getEvents());
      return true;
    });
  }
```

**Comment by vladmihalcea** [comment]
In order to include it in the docs, I need you to provide a Maven module with a Play example in this repository so that it can be used as a reference as well.

**Comment by eximius313** [comment]
PlayFramework uses `sbt`. Do you want to have `sbt` subproject?

**Comment by vladmihalcea** [comment]
This [Maven repository](https://vladmihalcea.com/books/high-performance-java-persistence/) shows it could be run from Maven too.

**Comment by eximius313** [comment]
Are you sure the link points to valid location?

**Comment by vladmihalcea** [comment]
Anyway, I wonder why you initialize Hypersistence Optimizer in a transaction.

```
jpaApi.withTransaction(em -> {
      final ListEventHandler listEventListener = new ListEventHandler();
      new HypersistenceOptimizer(
          new JpaConfig(em.getEntityManagerFactory())
                      .setEventHandler(new ChainEventHandler(
                              Arrays.asList(
                                      listEventListener,
                                      LogEventHandler.INSTANCE
                              )
                      ))
      ).init();

      assertEquals(0, listEventListener.getEvents());
      return true;
    });
  }
```

That shouldn't be needed. Hypersistence Optimizer just scans the provided EntityManagerFactory and it does not need to do that in the context of a transaction.

**Comment by eximius313** [comment]
Without it Play was throwing:
```
java.lang.RuntimeException: No EntityManager bound to this thread. Try wrapping this call in JPAApi.withTransaction, or ensure that the HTTP context is setup on this thread., took 14.951 sec
[error]     at play.db.jpa.JPAEntityManagerContext.em(JPAEntityManagerContext.java:35)
[error]     at play.db.jpa.DefaultJPAApi.em(DefaultJPAApi.java:89)
```
But I didn't consider it important enough to investigate.

**Comment by vladmihalcea** [comment]
That does not look like an exception thrown by Hibernate Optimizer. As long as you have a reference to an EntityManagerFactory, it will just work as explained in the docs. Therefore, this is issue is about how you can get such a reference in Play, which has nothing to do with Hypersistence Optimizer.

**Comment by eximius313** [comment]
Of course. I've never said it's `Hypersistence Optimizer` problem.
I just saw, that User Guide includes `Hypersistence Optimizer Spring Boot configuration`, so I thought I could share the configuration in Play Framework as well. Just it.

**Comment by vladmihalcea** [comment]
In this case, I'd use that jpaAPi to fetch the current EntityManagerFactory and then call Hypersistence Optimizer as stated in the docs.

Anyway, it looks like a limitation that you can't just inject the EntityManagerFactory directly without opening an EntityManager. Does it not have a bootstrap call back for that?

**Comment by eximius313** [comment]
I'll look for the solution

**Comment by vladmihalcea** [comment]
Fixed.

Check out the [dedicated section](https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/#play-framework-configuration). Since I don't have Play, I didn't test it. However, you might want to validate the solution and let me know if my approach is fine.  just followed the Play documentation and extracted the `EntityManagerFactory` so that it can be passed to HypersistenceOptimizer.

**Comment by eximius313** [comment]
It works the way you described it

**Comment by vladmihalcea** [comment]
Great, thanks for testing it. It's better to extract the `EntityManagerFactory` and close the current `EntityManager` and JPA transaction. Otherwise, the scanning happens in the context of a database transaction.
