### ISSUE TITLE
TableRowAlreadyManagedEvent is triggered for entities using SINGLE_TABLE inheritance

### ISSUE THREAD

**Issue by bogdhy** [vladmihalcea/hypersistence-optimizer#244]
Hello Vlad,

From what I've understood from the TableRowAlreadyManagedEvent documentation this is triggered when you load two different entities that point to the same database table record.

But in our case, this was reported for entities that point to a different record:
![image](https://github.com/vladmihalcea/hypersistence-optimizer/assets/12337250/322e3b05-a28d-48d4-87ba-cdccfcce0984)

This is how the records are defined:

![image](https://github.com/vladmihalcea/hypersistence-optimizer/assets/12337250/45e48c9f-e73e-4481-a4e5-064c6047379c)

![image](https://github.com/vladmihalcea/hypersistence-optimizer/assets/12337250/19ef2a9f-1725-4623-ab66-bae72b6bad51)

![image](https://github.com/vladmihalcea/hypersistence-optimizer/assets/12337250/35b4eebe-bcd6-4929-b737-4a6bcf730b5b)

Let me know if you need more information.

Best,
Bogdan

**Comment by vladmihalcea** [comment]
I think it's because of the entity inheritance. Could you provide a replicating test case in the test repository? 

You can use [this test case](https://github.com/vladmihalcea/hypersistence-optimizer/blob/master/hypersistence-optimizer-test-case/src/test/java/io/hypersistence/optimizer/config/mapping/association/fetching/eager/EagerFetchingManyToOneTest.java) as a template for your replicating test case.

**Comment by bogdhy** [comment]
Hello,

Here is the [test case](https://github.com/bogdhy/hypersistence-optimizer/blob/master/hypersistence-optimizer-test-case/src/test/java/io/hypersistence/optimizer/hibernate/event/session/TableRowAlreadyManagedEventTest.java) but it seems that with Hibernate 6 the `TableRowAlreadyManagedEvent` is not dispached.

Do you have any guidelines on how to run the test with Hibernate 5.6?

The version on our end is <hibernate.version>**5.6.15.Final**</hibernate.version>

Best,
Bogdan

**Comment by vladmihalcea** [comment]
There are branches for every Hibernate version. For instance, [this is the Hibernate 5.6 branch](https://github.com/vladmihalcea/hypersistence-optimizer/tree/5.6).

But, don't worry, I will use the provided test case as a reference to see if I can replicate it on older Hibernate versions. I'll let you know if I can't replicate it.

**Comment by vladmihalcea** [comment]
@bogdhy I managed to replicate it and will provide a fix for it in the next version that will be released soon.

**Comment by bogdhy** [comment]
@vladmihalcea glad I could help.

I'm looking forward for the new release.

All the best,
Bogdan

**Comment by vladmihalcea** [comment]
Fixed.
