### ISSUE TITLE
Provide more details to the ElementCollectionEvent and lower its priority

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/hypersistence-optimizer#25]
The `ElementCollectionEvent` should have a `MAJOR` priority, not a `CRITICAL` one.

Also, as illustrated by [the discussion on this GitHub issue](https://github.com/vladmihalcea/hypersistence-optimizer/issues/20), it's worth adding more details about why using an element collection is not as efficient as a bidirectional one-to-many association.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by eximius313** [comment]
If using Set or Map with `ElementCollection` is not efficient - I'd love to read an article why. 
Changing enums used with `ElementCollection` to Entities just to have bidirectional relation is major change in business model

**Comment by vladmihalcea** [comment]
I have updated the User Guide with more details. I'll surely write an article as well in the near future.
