### ISSUE TITLE
Add license to the hypersistence-optimizer GitHub repository

### ISSUE THREAD

**Issue by marekkapowicki** [vladmihalcea/hypersistence-optimizer#26]
As the repository doesn't have license, we cannot use or modify it. It's all rights reserved
I there any possibility to add the license and define the meaning of trial

**Comment by vladmihalcea** [comment]
I fixed the issue by adding the [Apache v2 License](https://github.com/vladmihalcea/hypersistence-optimizer/blob/master/LICENSE) for this particular repository.

However, this repository is just for examples and test cases. The actual product has a [commercial license](https://vladmihalcea.com/hypersistence-optimizer/license/) which documents the trial version as well.
