### ISSUE TITLE
Unable to download sources for Hibernate52Service

### ISSUE THREAD

**Issue by neerajjain92** [vladmihalcea/hypersistence-optimizer#4]
When i click on download sources button nothing happens, looks like there are no java-doc for this class.
<img width="1412" alt="Screenshot 2019-03-20 at 4 42 21 PM" src="https://user-images.githubusercontent.com/11440750/54680167-2fdbf080-4b2f-11e9-984d-8085aed20650.png">

**Comment by vladmihalcea** [comment]
The sources for the `Service` and `Scanner` are not included currently. You don't even need them to use the framework.

**Comment by neerajjain92** [comment]
@vladmihalcea I was debugging the library to figure out why #3 is failing.

**Comment by vladmihalcea** [comment]
@neerajjain92 You don't need to debug an issue in the scanner as the API requires you a very deep understanding of Hibernate internals. That's why sources and JavaDocs are not useful for the internal classes. You just need to provide the mapping of the entities that fail, and I'll fix the issues.

**Comment by vladmihalcea** [comment]
Won't fix.
