### ISSUE TITLE
Add the entityClass property in the EntityMappingEvent to store the entity class that triggered the event

### ISSUE THREAD

**Issue by jeffjensen** [vladmihalcea/hypersistence-optimizer#88]
When an entity has a flagged event and not going to change the entity, how can we disable that event notification for that entity/entity+field only, and keep reporting that event for other entities?

We can set EventFilters to suppress events for all entities.  How can we suppress events for a specific entity?

Couple of ideas:
1. Config HO to automatically disable notification on specified ones
    1. Enhance `Config` with `addSuppression(Suppression)` - `Suppression` contains 3 fields: event name, class name, and field name.
    1. Have a text file with event name, class name, and field name and HO automatically disables notification on those.
1. Create a more complex `EventFilter`, but requires class name and field name accessors - the Event interface does not expose methods to inspect, such as a `getClassName()` and `getFieldName()`.

**Comment by vladmihalcea** [comment]
That's a good idea. Currently, you can filter events using `instanceOf` in `EventFilter`. The approach is, actually, very flexible. You can define a `Map<Class<? extends Event>, List<Class>>` where you specify what entity classes should skip an event, and apply the filtering logic accordingly.

I'll also think of a way to address this after I add support for reading properties from the Hibernate settings as well.

**Comment by jeffjensen** [comment]
> You can define a Map<Class<? extends Event>, List<Class>> where you specify what entity classes should skip an event, and apply the filtering logic accordingly.

Do you mean that's possible now?  To obtain the class name in the event, do you parse it from `getDescription()`?

**Comment by vladmihalcea** [comment]
Yes. You can use the `event.getEntityName()` if the event extends `EntityMappingEvent`.

**Comment by vladmihalcea** [comment]
Fixed.
