### ISSUE TITLE
Locate the add/remove bidirectional synchronization methods in the entity superclasses

### ISSUE THREAD

**Issue by jeffjensen** [vladmihalcea/hypersistence-optimizer#96]
BidirectionalSynchronizationEvent seems to look for method add and remove methods in the current class but not parent classes as this rule fails on a situation where we have the methods in a parent class.  Is this accurate?

**Comment by vladmihalcea** [comment]
Thanks for spotting it. I could replicate it and will be fixed in 2.2. Stay tuned for more awesome checks that will be added.

**Comment by vladmihalcea** [comment]
Fixed.
